platform :ios, '6.0'
pod 'Foursquare-iOS-API', '~> 1.1.0'
pod 'socket.IO', local: './Libraries/socket.IO'
pod 'SocketRocket', local: './Libraries/SocketRocket'
pod 'AFNetworking', '~> 1.1.0'
pod 'SDWebImage', '~> 3.1.x'
